#:schema node_modules/wrangler/config-schema.json
name = "studyhub"
main = ".open-next/worker.js"

compatibility_date = "2026-04-19"
compatibility_flags = ["nodejs_compat"]

[alias]
"@mongodb-js/saslprep" = "./node_modules/@mongodb-js/saslprep/dist/node.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
